apiVersion: apps/v1
kind: Deployment
metadata:
  name: allin1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archon
      component: allin1
  template:
    metadata:
      labels:
        app: archon
        component: allin1
    spec:
      containers:
        args:
          ["/archon/archon", "--core", "--migrate", "--orchestrator", "--worker"]