apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app: archon
      component: core
nameSuffix: core
resources:
  - ../../base
  - ingress.yaml
namespace: modrinth
patches:
  - target:
      kind: Deployment
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: core
      spec:
        selector:
          matchLabels:
            app: archon
            component: core
        template:
          metadata:
            labels:
              app: archon
              component: core
          spec:
            containers:
              - name: archon
                args: ["/archon/archon", "--core"]