apiVersion: apps/v1
kind: Deployment
metadata:
  name: archon-
spec:
  replicas: 1
  selector:
    matchLabels:
      app: archon
  template:
    metadata:
      labels:
        app: archon
    spec:
      containers:
        - name: archon
          image: archon
          imagePullPolicy: IfNotPresent
          args: ["/archon/archon"]
          envFrom:
            - configMapRef:
                name: archon-config
            - secretRef:
                name: cnpg-archon-app
          env:
            - name: RUST_LOG
              value: info,archon=debug
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cnpg-archon-app
                  key: uri
            - name: DATABASE_MIN_CONNECTIONS
              value: "4"
            - name: DATABASE_MAX_CONNECTIONS
              value: "16"
            - name: REDIS_URL
              value: redis://rfs-redis-fo-archon.modrinth-infra.svc.cluster.local:26379
            - name: REDIS_MAX_CONNECTIONS
              value: "128"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8000"
            - name: SELF_ADDR
              value: "http://modrinth-archon"
            - name: CLICKHOUSE_URL
              value: http://clickhouse-cluster-clickhouse-headless.modrinth-infra.svc.cluster.local:8123
            - name: CLICKHOUSE_USER
              value: default
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-password-default
                  key: password
            - name: CLICKHOUSE_DATABASE
              value: archon
            - name: CLICKHOUSE_USE_VALIDATION
              value: "1"
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: "1"
              memory: "128Mi"
            limits:
              cpu: "2"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
            initialDelaySeconds: 0
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 1
            initialDelaySeconds: 0
            failureThreshold: 9
