apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespaces.yaml
  - ../services/archon/components/allin1
  - ../infra/seaweefs-s3
  - ../infra/registry
  - ../infra/buildkit
  - ./ingresses/archon-gateway.yaml
components:
  - ./images
generatorOptions:
  disableNameSuffixHash: true
