apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespaces.yaml
  - ../services/archon/components/core
  - ../services/archon/components/orchestrator
  - ../services/archon/components/worker
  - ../infra/seaweefs-s3
  - ../infra/registry
  - ../infra/buildkit
  - ../infra/clickhouse
  - ../infra/rfo
  - ../infra/cnpg/clusters
  - ./ingresses/archon-gateway.yaml
components:
  - ./images
generatorOptions:
  disableNameSuffixHash: true
