apiVersion: v1
kind: Namespace
metadata:
  name: modrinth
  labels:
    gateway-access: "true"

---
apiVersion: v1
kind: Namespace
metadata:
  name: modrinth-infra

---
apiVersion: v1
kind: Namespace
metadata:
  name: redis-operator

---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-gateway
