apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: modrinth-infra
resources:
  - service.yaml
  - tailnet-service.yaml
  - deployment.yaml
configMapGenerator:
  - name: buildkitd-config
    files:
      - buildkitd.toml