apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: archon
    newName: modrinth-registry.cymric-polaris.ts.net:5000/archon
    newTag: latest@sha256:50c1694b42313ca732c11ba3f42bffb009eee2bde734ea2a85640dc5346ff7d2
  - name: labrinth
    newName: modrinth-registry.cymric-polaris.ts.net:5000/labrinth
    newTag: a6d359e9c1c80b39eab9279494d83a49bd2be39b