apiVersion: apps/v1
kind: Deployment
metadata:
  name: labrinth-
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labrinth
  template:
    metadata:
      labels:
        app: labrinth
    spec:
      containers:
        - name: labrinth
          image: labrinth
          imagePullPolicy: IfNotPresent
          args: ["/labrinth/labrinth"]
          envFrom:
            - configMapRef:
                name: labrinth-config
            - secretRef:
                name: cnpg-labrinth-app
          env:
            - name: RUST_LOG
              value: info,labrinth=debug
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: cnpg-labrinth-app
                  key: uri
            - name: DATABASE_MIN_CONNECTIONS
              value: "4"
            - name: DATABASE_MAX_CONNECTIONS
              value: "32"
            - name: REDIS_URL
              value: redis://redis-labrinth-redis.modrinth-infra.svc.cluster.local:6379
            - name: REDIS_MAX_CONNECTIONS
              value: "256"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8000"
            - name: SELF_ADDR
              value: "http://modrinth-labrinth"
            - name: CLICKHOUSE_URL
              value: http://clickhouse-cluster-clickhouse-headless.modrinth-infra.svc.cluster.local:8123
            - name: CLICKHOUSE_USER
              value: default
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clickhouse-password-default
                  key: password
            - name: CLICKHOUSE_DATABASE
              value: labrinth
            - name: CLICKHOUSE_REPLICATED
              value: "false"
            - name: ARCHON_URL
              value: http://archon-core.modrinth.svc.cluster.local
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: "1"
              memory: "128Mi"
            limits:
              cpu: "4"
              memory: "2Gi"
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            initialDelaySeconds: 0
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 1
            initialDelaySeconds: 0
            failureThreshold: 9
