kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app: labrinth
      component: httpserver
nameSuffix: httpserver
resources:
  - ../../base
  - ingress.yaml
namespace: modrinth
patches:
  - target:
      kind: Deployment
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: httpserver
      spec:
        selector:
          matchLabels:
            app: labrinth
            component: httpserver
        template:
          metadata:
            labels:
              app: labrinth
              component: httpserver
          spec:
            containers:
              - name: labrinth
                args: ["/labrinth/labrinth", "--no-background-tasks"]