apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: labrinth
spec:
  instances: 1
  storage:
    size: 4Gi
  bootstrap:
    initdb:
      database: labrinth
      owner: modrinth
  enableSuperuserAccess: true
  superuserSecret:
    name: labrinth-psql-postgres
  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: psql-labrinth
              annotations:
                tailscale.com/hostname: modrinth-psql-labrinth
            spec:
              type: LoadBalancer
              loadBalancerClass: tailscale
    roles:
      - name: labrinth
        ensure: present
        login: true
        passwordSecret:
          name: labrinth-psql-labrinth