apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: modrinth-infra
namePrefix: redis-fo-
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: modrinth-stack
resources:
  - archon-failover.yaml