apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: labrinth-redis
  namespace: modrinth-infra
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.15
    imagePullPolicy: IfNotPresent
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 512Mi